export const ServerSettings = [
  "ServerName",
  "ServerDescription",
  "AdminPassword",
  "ServerPassword",
  "PublicIP",
  "PublicPort",
  "ServerPlayerMaxNum",
  "bIsUseBackupSaveData",
  "AutoSaveSpan",
  "CrossplayPlatforms",
  "LogFormatType",
  "RandomizerType",
  "RandomizerSeed",
  "bIsRandomizerPalLevelRandom",
];

export const InGameSettings = [
  "DayTimeSpeedRate",
  "NightTimeSpeedRate",
  "ExpRate",
  "PalCaptureRate",
  "PalSpawnNumRate",
  "PalDamageRateAttack",
  "PalDamageRateDefense",
  "PalStomachDecreaceRate",
  "PalStaminaDecreaceRate",
  "PalAutoHPRegeneRate",
  "PalAutoHpRegeneRateInSleep",
  "PlayerDamageRateAttack",
  "PlayerDamageRateDefense",
  "PlayerStomachDecreaceRate",
  "PlayerStaminaDecreaceRate",
  "PlayerAutoHPRegeneRate",
  "PlayerAutoHpRegeneRateInSleep",
  "BuildObjectHpRate",
  "BuildObjectDamageRate",
  "BuildObjectDeteriorationDamageRate",
  "DropItemMaxNum",
  "PhysicsActiveDropItemMaxNum",
  "ItemWeightRate",
  "CollectionDropRate",
  "CollectionObjectHpRate",
  "CollectionObjectRespawnSpeedRate",
  "EnemyDropItemRate",
  "PalEggDefaultHatchingTime",
  "MonsterFarmActionSpeedRate",
  "bEnableInvaderEnemy",
  "EnablePredatorBossPal",
  "DeathPenalty",
  "GuildPlayerMaxNum",
  "BaseCampMaxNumInGuild",
  "BaseCampWorkerMaxNum",
  "MaxBuildingLimitNum",
  "SupplyDropSpan",
  "ChatPostLimitPerMinute",
  "EquipmentDurabilityDamageRate",
  "ItemContainerForceMarkDirtyInterval",
  "PlayerDataPalStorageUpdateCheckTickInterval",
  "ItemCorruptionMultiplier",
];

export const AdvancedSettings = [
  "bEnablePlayerToPlayerDamage",
  "bEnableFriendlyFire",
  "bActiveUNKO",
  "bEnableAimAssistPad",
  "bEnableAimAssistKeyboard",
  "DropItemMaxNum_UNKO",
  "BaseCampMaxNum",
  "DropItemAliveMaxHours",
  "bAutoResetGuildNoOnlinePlayers",
  "AutoResetGuildTimeNoOnlinePlayers",
  "WorkSpeedRate",
  "bIsMultiplay",
  "bIsPvP",
  "bHardcore",
  "bPalLost",
  "bCharacterRecreateInHardcore",
  "bCanPickupOtherGuildDeathPenaltyDrop",
  "bEnableNonLoginPenalty",
  "bEnableFastTravel",
  "bIsStartLocationSelectByMap",
  "bExistPlayerAfterLogout",
  "bEnableDefenseOtherGuildPlayer",
  "bInvisibleOtherGuildBaseCampAreaFX",
  "bBuildAreaLimit",
  "ServerReplicatePawnCullDistance",
  "bShowPlayerList",
  "bAllowGlobalPalboxExport",
  "bAllowGlobalPalboxImport",
  "RCONEnabled",
  "RCONPort",
  "RESTAPIEnabled",
  "RESTAPIPort",
  "Region",
  "bUseAuth",
  "BanListURL",
  "bEnableFastTravelOnlyBaseCamp",
  "bAllowClientMod",
  "bIsShowJoinLeftMessage",
  "DenyTechnologyList",
  "GuildRejoinCooldownMinutes",
  "AutoTransferMasterCheckIntervalSeconds",
  "AutoTransferMasterThresholdDays",
  "MaxGuildsPerFrame",
  "BlockRespawnTime",
  "RespawnPenaltyDurationThreshold",
  "RespawnPenaltyTimeScale",
  "bDisplayPvPItemNumOnWorldMap_BaseCamp",
  "bDisplayPvPItemNumOnWorldMap_Player",
  "AdditionalDropItemWhenPlayerKillingInPvPMode",
  "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
  "bAdditionalDropItemWhenPlayerKillingInPvPMode",
  "bEnableVoiceChat",
  "VoiceChatMaxVolumeDistance",
  "VoiceChatZeroVolumeDistance",
  "bAllowEnhanceStat_Health",
  "bAllowEnhanceStat_Attack",
  "bAllowEnhanceStat_Stamina",
  "bAllowEnhanceStat_Weight",
  "bAllowEnhanceStat_WorkSpeed",
  "bEnableBuildingPlayerUIdDisplay",
  "BuildingNameDisplayCacheTTLSeconds",
];

export const EntryIdToEnumName: Record<string, string> = {
  DeathPenalty: "EPalOptionWorldDeathPenalty",
  Difficulty: "EPalOptionWorldDifficulty",
  LogFormatType: "EPalOptionWorldLogFormatType",
  RandomizerType: "EPalRandomizerType",
  CrossplayPlatforms: "EPalAllowConnectPlatform",
  DenyTechnologyList: "EPalDenyTechnology", // 假设的枚举类型名称
}

export const SettingSections = [
  { id: "game", name: "游戏内设置" },
  { id: "server", name: "服务器设置" },
  { id: "advanced", name: "高级设置" },
] as const;

export const SettingGroups = [
  {
    id: "world",
    name: "世界与倍率",
    section: "game",
    icon: "globe",
    description: "时间、经验、随机化、空投和世界通用倍率。",
    settings: [
      "Difficulty",
      "RandomizerType",
      "RandomizerSeed",
      "bIsRandomizerPalLevelRandom",
      "DayTimeSpeedRate",
      "NightTimeSpeedRate",
      "ExpRate",
      "WorkSpeedRate",
      "SupplyDropSpan",
      "EnablePredatorBossPal",
      "ItemCorruptionMultiplier",
    ],
  },
  {
    id: "player",
    name: "玩家",
    section: "game",
    icon: "user",
    description: "玩家伤害、生存消耗、恢复、负重和装备耐久。",
    settings: [
      "PlayerDamageRateAttack",
      "PlayerDamageRateDefense",
      "PlayerStomachDecreaceRate",
      "PlayerStaminaDecreaceRate",
      "PlayerAutoHPRegeneRate",
      "PlayerAutoHpRegeneRateInSleep",
      "ItemWeightRate",
      "EquipmentDurabilityDamageRate",
    ],
  },
  {
    id: "pal",
    name: "帕鲁",
    section: "game",
    icon: "paw",
    description: "捕获、刷新、战斗、生存消耗、恢复、孵蛋和牧场效率。",
    settings: [
      "PalCaptureRate",
      "PalSpawnNumRate",
      "PalDamageRateAttack",
      "PalDamageRateDefense",
      "PalStomachDecreaceRate",
      "PalStaminaDecreaceRate",
      "PalAutoHPRegeneRate",
      "PalAutoHpRegeneRateInSleep",
      "PalEggDefaultHatchingTime",
      "MonsterFarmActionSpeedRate",
    ],
  },
  {
    id: "build",
    name: "建筑与采集",
    section: "game",
    icon: "hammer",
    description: "建筑耐久、建造限制、采集资源和建筑显示。",
    settings: [
      "BuildObjectHpRate",
      "BuildObjectDamageRate",
      "BuildObjectDeteriorationDamageRate",
      "CollectionDropRate",
      "CollectionObjectHpRate",
      "CollectionObjectRespawnSpeedRate",
      "MaxBuildingLimitNum",
      "bBuildAreaLimit",
      "bEnableBuildingPlayerUIdDisplay",
    ],
  },
  {
    id: "drop",
    name: "掉落物",
    section: "game",
    icon: "package",
    description: "敌人掉落、世界掉落物数量和保留时长。",
    settings: [
      "EnemyDropItemRate",
      "DropItemMaxNum",
      "PhysicsActiveDropItemMaxNum",
      "DropItemMaxNum_UNKO",
      "DropItemAliveMaxHours",
    ],
  },
  {
    id: "mode",
    name: "游戏规则",
    section: "game",
    icon: "flag",
    description: "死亡惩罚、PvE/PvP 规则、硬核、快速传送和出生逻辑。",
    settings: [
      "DeathPenalty",
      "bEnablePlayerToPlayerDamage",
      "bEnableFriendlyFire",
      "bEnableInvaderEnemy",
      "bActiveUNKO",
      "bEnableAimAssistPad",
      "bEnableAimAssistKeyboard",
      "bIsMultiplay",
      "bIsPvP",
      "bHardcore",
      "bPalLost",
      "bCharacterRecreateInHardcore",
      "bCanPickupOtherGuildDeathPenaltyDrop",
      "bEnableNonLoginPenalty",
      "bEnableFastTravel",
      "bEnableFastTravelOnlyBaseCamp",
      "bIsStartLocationSelectByMap",
      "bExistPlayerAfterLogout",
      "bEnableDefenseOtherGuildPlayer",
      "bInvisibleOtherGuildBaseCampAreaFX",
    ],
  },
  {
    id: "guild",
    name: "公会与据点",
    section: "game",
    icon: "users",
    description: "据点数量、据点帕鲁、公会人数和会长转让。",
    settings: [
      "BaseCampMaxNum",
      "BaseCampMaxNumInGuild",
      "BaseCampWorkerMaxNum",
      "bAutoResetGuildNoOnlinePlayers",
      "AutoResetGuildTimeNoOnlinePlayers",
      "GuildPlayerMaxNum",
      "GuildRejoinCooldownMinutes",
      "AutoTransferMasterCheckIntervalSeconds",
      "AutoTransferMasterThresholdDays",
    ],
  },
  {
    id: "pvp",
    name: "PvP",
    section: "game",
    icon: "swords",
    description: "PvP 重生惩罚、地图物资显示和击杀额外掉落。",
    settings: [
      "BlockRespawnTime",
      "RespawnPenaltyDurationThreshold",
      "RespawnPenaltyTimeScale",
      "bDisplayPvPItemNumOnWorldMap_BaseCamp",
      "bDisplayPvPItemNumOnWorldMap_Player",
      "AdditionalDropItemWhenPlayerKillingInPvPMode",
      "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
      "bAdditionalDropItemWhenPlayerKillingInPvPMode",
    ],
  },
  {
    id: "stat",
    name: "能力强化",
    section: "game",
    icon: "trend",
    description: "帕鲁精髓强化生命、攻击、耐力、负重和工作速度。",
    settings: [
      "bAllowEnhanceStat_Health",
      "bAllowEnhanceStat_Attack",
      "bAllowEnhanceStat_Stamina",
      "bAllowEnhanceStat_Weight",
      "bAllowEnhanceStat_WorkSpeed",
    ],
  },
  {
    id: "server",
    name: "服务器",
    section: "server",
    icon: "server",
    description: "服务器名称、简介、人数、存档、Mod 和跨界帕鲁箱。",
    settings: [
      "ServerName",
      "ServerDescription",
      "ServerPlayerMaxNum",
      "CoopPlayerMaxNum",
      "AutoSaveSpan",
      "bIsUseBackupSaveData",
      "bAllowClientMod",
      "bAllowGlobalPalboxExport",
      "bAllowGlobalPalboxImport",
      "bIsShowJoinLeftMessage",
    ],
  },
  {
    id: "network",
    name: "网络与安全",
    section: "server",
    icon: "shield",
    description: "跨平台、区域、认证、封禁名单、日志和聊天限制。",
    settings: [
      "CrossplayPlatforms",
      "LogFormatType",
      "Region",
      "bUseAuth",
      "BanListURL",
      "bShowPlayerList",
      "ChatPostLimitPerMinute",
    ],
  },
  {
    id: "voice",
    name: "语音聊天",
    section: "server",
    icon: "mic",
    description: "游戏内近距离语音开关和距离衰减。",
    settings: [
      "bEnableVoiceChat",
      "VoiceChatMaxVolumeDistance",
      "VoiceChatZeroVolumeDistance",
    ],
  },
  {
    id: "advanced",
    name: "高级参数",
    section: "advanced",
    icon: "sliders",
    description: "同步距离、容器刷新、帕鲁仓库检查、禁用科技和性能参数。",
    settings: [
      "ServerReplicatePawnCullDistance",
      "ItemContainerForceMarkDirtyInterval",
      "PlayerDataPalStorageUpdateCheckTickInterval",
      "DenyTechnologyList",
      "MaxGuildsPerFrame",
      "BuildingNameDisplayCacheTTLSeconds",
    ],
  },
] as const;
